name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # --- TRABAJO 1: PRUEBAS DE CALIDAD ---
  test-and-analyze:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4' # <--- Tu versión correcta
        extensions: mbstring, bcmath, pdo, pdo_mysql

    - name: Install Dependencies
      run: composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts

    - name: Copy .env
      run: cp .env.example .env

    - name: Generate Key
      run: php artisan key:generate

    - name: Run Static Analysis (Larastan)
      run: ./vendor/bin/phpstan analyse --memory-limit=2G

    - name: Run Tests (PHPUnit)
      run: php artisan test

  # --- TRABAJO 2: CONSTRUCCIÓN Y SEGURIDAD ---
  build-push-docker:
    needs: test-and-analyze
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 1. Construimos la imagen PERO NO la subimos todavía (load: true)
      # Esto permite que Trivy la pueda leer localmente
      - name: Build Docker Image locally
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: aarondevops/bodega-api:latest

      # 2. Escaneamos la imagen con Trivy
      # Si encuentra errores CRÍTICOS (CRITICAL), detiene el proceso (exit-code: 1)
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'aarondevops/bodega-api:latest'
          format: 'table'
          exit-code: '1' # Falla si encuentra riesgos
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      # 3. Si Trivy da luz verde, entonces SÍ subimos la imagen (push: true)
      - name: Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: aarondevops/bodega-api:latest


      # --- TRABAJO 3: DESPLIEGUE EN VM LOCAL (ANSIBLE) ---
  deploy-to-vm:
    needs: build-push-docker # Espera a que se construya la imagen
    runs-on: self-hosted     # <--- ¡LA MAGIA! Corre en tu PC
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Ansible Playbook
        run: ansible-playbook deploy.yml    